[package]
name = "ping"
version = "0.3.0"
authors = ["An Long <aisk1988@gmail.com>"]
license = "MIT"
description = "ICMP library"
repository = "https://github.com/aisk/ping"
edition = "2018"

[dependencies]
socket2 = "0.3"
thiserror = "1.0"
rand = "0.7"
